### PR TITLE
encode json with indent

### PR DESCRIPTION
**Pull request by QianChenglong**
Change standard library of json to github.com/klauspost/json in order to encode json with indent.
So it will be human readable when debug.

### CODE REVIEW

**Comment by elithrar** [comment]
Adding white space (indentation) to all output is not a great idea: it may add a non-negligible overhead to the output. This might be better handled in a `Indent(prefix, indent string)` method on `Server`. 

Note that the standard library supports indentation: http://golang.org/pkg/encoding/json/#MarshalIndent - the method would be better wrapping that rather than pulling in a third party dependency.

**Comment by elithrar** [comment]
PS: If it's just for debugging you could integrate this functionality into
your logger, and/or use a command-line tool to pipe the output through
rather than push it into the library.

**Comment by QianChenglong** [comment]
Thans for your reply.
But in our project, the user of my api want easy to read response.
May be an switch method better?

**Comment by elithrar** [comment]
Yes - I'm saying that making the library (by default) indent JSON isn't a great idea, but that it can be easily added (with a single line) to a library user's program - e.g.

```go

b, err := json.EncodeClientRequest(...)
if err != nil {
    return err
}

var buf bytes.Buffer
err = json.Indent(&buf, b, "", "\t")
if err != nil {
    return err
}

// We now have indented JSON in `buf`
```

This uses the `json.Indent` function from the standard library: https://golang.org/pkg/encoding/json/#Indent

The alternative would be to add this as a global variable to the package, but I don't think that's a particularly great way to go as it's "all or nothing".

Hope that helps.

**Pull request closed without merging**
