### PR TITLE
Pass the correct status code to AfterFunc

### PR DESCRIPTION
**Pull request by colega**
We're passing a 200 even when we respond 400 to the client.

### CODE REVIEW

**Comment by kisielk** [comment]
Can you please add a test for this? 
Also change the code to use `http.StatusOK` and `http.StatusBadRequest` instead of bare numbers.
Thank you.

**Comment by colega** [comment]
Hey, of course, changed the status codes to use `http` package. 
Can we solve https://github.com/gorilla/rpc/pull/64 before adding tests so I wouldn't have to solve conflicts with myself?

**Comment by colega** [comment]
They can be merged in any order 👍

**Comment by kisielk** [comment]
Hi,

Can you please update so this can be applied to master?

**Comment by colega** [comment]
Sure! I've rebased the branch.

**Comment by kisielk** [comment]
Great, thanks for all your PRs. I've also tagged a new 1.2.0 release to include all your changes (and other stuff that's been piling up!)

**Pull request merged**
